@startuml
'https://plantuml.com/sequence-diagram
participant Client
participant RoomService
participant RoomValidationService
participant RoomRepository



autonumber 2.1

Client -> RoomService: get(RoomRequestId)
    activate RoomService
    RoomService -> RoomValidationService : validateId(RoomRequestId)
        activate RoomValidationService
    return boolean
    RoomService -> RoomRepository: get(RoomId)
        activate RoomRepository
    return Room
return Room
@enduml